server:
  port: 9099
  address: 0.0.0.0

spring:
  datasource:
    is-open: false
    mysql:
      username: root
      password: allinsql666
      jdbc-url: jdbc:mysql://172.22.0.2:3306/mmexptdataplatform?characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
    clickhouse:
      username: default
      password: allinsql666
      jdbc-url: jdbc:clickhouse://172.22.0.3:8123/all_in_sql?socket_timeout=3603000&max_execution_time=3602&compress=0
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

clickhouse:
  driver: com.clickhouse.jdbc.ClickHouseDriver
  devices:
    - id: 1
      url: jdbc:clickhouse://172.22.0.3:8123/all_in_sql?socket_timeout=3603000&max_execution_time=3602&compress=0
      user: default
      password: allinsql666

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  supportMethodsArguments: true

springdoc:
  swagger-ui:
    path: /api
  api-docs:
    path: /api/api-json-docs
  paths-to-match: /api/**

logging:
  level:
    root: info
