name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: build-environment.yml
          cache-environment: true

      - name: Build the JupyterLite site
        shell: bash -l {0}
        run: |
          jupyter lite build --contents docs/ipynbs --output-dir ipynb

      - name: Upload JupyterLite site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ipynb
          name: ipynb

      - name: Setup Causal Inference HTML Pages
        uses: actions/configure-pages@v5

      - name: Upload Causal Inference HTML artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          name: html

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: page-url
      url: 'https://tencent.github.io/fast-causal-inference'

    runs-on: ubuntu-latest
    steps:
      - name: Download JupyterLite site artifact
        uses: actions/download-artifact@v4
        with:
          name: ipynb

      - name: Download Causal Inference HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: html

      - name: Deploy JupyterLite site to GitHub Pages
        id: deployment_jupyterlite
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./ipynb
          name: ipynb

      - name: Deploy Causal Inference HTML to GitHub Pages
        id: deployment_html
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./docs
          name: html

